// Highest peaks for national parks: [name, elevation in feet]
export const parkPeaks = {
    "Acadia": ["Cadillac Mountain", 1530],
    "Arches": ["Elephant Butte", 5653],
    "Badlands": ["Sheep Mountain Table", 3300],
    "Big Bend": ["Emory Peak", 7825],
    "Black Canyon of the Gunnison": ["Warner Point", 8572],
    "Bryce Canyon": ["Rainbow Point", 9115],
    "Canyonlands": ["Cathedral Point", 7120],
    "Capitol Reef": ["Cathedral Valley", 7000],
    "Carlsbad Caverns": ["Guadalupe Peak", 8751],
    "Channel Islands": ["Devils Peak", 2450],
    "Crater Lake": ["Mount Scott", 8929],
    "Cuyahoga Valley": ["Beaver Point", 1164],
    "Death Valley": ["Telescope Peak", 11043],
    "Denali": ["Denali", 20310],
    "Everglades": ["Long Pine Key", 7],
    "Gateway Arch": ["Gateway Arch", 630],
    "Glacier": ["Mount Cleveland", 10466],
    "Grand Canyon": ["Point Imperial", 8803],
    "Grand Teton": ["Grand Teton", 13775],
    "Great Smoky Mountains": ["Clingmans Dome", 6643],
    "Indiana Dunes": ["Mount Tom", 192],
    "Joshua Tree": ["Quail Mountain", 5814],
    "Mesa Verde": ["Park Point", 8571],
    "Mount Rainier": ["Mount Rainier", 14411],
    "Olympic": ["Mount Olympus", 7965],
    "Rocky Mountain": ["Longs Peak", 14259],
    "Saguaro": ["Rincon Peak", 8482],
    "Sequoia": ["Mount Whitney", 14505],
    "Shenandoah": ["Hawksbill", 4051],
    "Voyageurs": ["Kabetogama Peninsula", 1400],
    "Wind Cave": ["Rankin Ridge", 5013],
    "Yellowstone": ["Eagle Peak", 11358],
    "Yosemite": ["Mount Lyell", 13114],
    "Zion": ["Horse Ranch Mountain", 8726]
}; 